views/pages/index.ejs
These changes create our initial coin board game divs with unique ids, customer area divs with unique ids, and buttons with ids for us to select and add functionality to later.
=> [finishes #184921201] For real this time

views/pages/index.html, views/scripts/coinJarAddCoins.js, views/scripts/coinPile.js, views/scripts/resetButton.js, views/styles/devCoins.css
Here's the hopefully good pull request.
Made several changes compared to the HTML in main, they are required for the JavaScript I wrote to work.
=> Dhaley coin class new

index.html, views/scripts/coinJarAddCoins.js
fixes images, css, and javascript not working on render.
=> move index to root, change paths again

index.html, views/scripts/coinPile.js, views/scripts/coinProperties.js
This will make it so when clicked on, the td (not the image itself, but the td the image is in) will call a function which instantiates a coin object based on the td clicked, and display its properties to the console using the object's toString function.
=> [finishes #184980928] add console coin properties

index.html, scripts/coinPile.js, scripts/moveCoin.js
Should add proper functionality for clicking a coin onto another coin to attempt to merge them.
Can only merge coins of the same type, except for 2 dimes + 1 nickel = 1 quarter.
Merge will also fail if the number of coins doesn't work out into 1 even pile (3 penny + 3 penny = 1 nickel 1 penny, so failure)
Dollars cannot merge, as we determined they were the "final" stage of the merging.
Also removes draggable images.
=> Merge Coins Functionality

index.html, scripts/customer.js, styles/devCoins.css
This is my second PR for the topic. I cleaned up my logic to prevent 0.00 displaying. I added a file customer.js that has functions to randomize coinPiles and assign them types & count. Added CSS so the divs were visible for where the customer change needs to be placed. Along with adding a div with a temporary picture for a "customer"
=> [finsihes #185013933] Customer Request Generation 

index.html, scripts/loadSaveGame.js, scripts/popUpEvents.js, styles/site.css
If you would like to try out the local storage multipule times, you can clear your local storage while the website is up in the console log by typing: ```localstorage.removeItem("gameBoard"); ``` _(Localstorage only works per website so this won't corrupt any data for anything else that you use that uses localstorage to save data)_
Updated Video:
https://user-images.githubusercontent.com/123593329/235292659-cade24d1-1e3f-40b3-9ea8-a23b943be88a.mp4
=> Load & Save Implemented

index.html, scripts/custCoinCheck.js, scripts/customer.js, scripts/moveCoin.js, styles/devCoins.css
The code so far for moving coins into the customer boxes
=> start of coinCheck

scripts/coinPile.js, scripts/customer.js
Customer still displays in cents but values are now ints to help with random floating problems
=> Changed floats to ints coin values

scripts/moveCoin.js
created event listener with logic for when to apply that function
=> [finishes #185035200] added function eraseCoin to moveCoin.js file

index.html, scripts/moveCoin.js
=> [finishes #185035248] Added mergeCounter display

scripts/coinPile.js, scripts/custCoinCheck.js, scripts/moveCoin.js
Fixes #34, fixes #33
Dollars are now worth 100 cents, not 1.
td dataset attributes are removed from the original td when the held coin is placed elsewhere.
=> Debug davin

scripts/custCoinCheck.js, scripts/moveCoin.js
If you picked up a coin, and placed it back in the same spot, it would still clear the data, making the cell have no data, despite a coin being placed there. This fixes that
=> Fixes coin placement in same td

scripts/loadSaveGame.js
Fixed to save both customer board and game board. This also means both boards are being reset to clear all data on boards.
=> [finishes: #185083733] Save&Load Customer Board

index.html, scripts/coinJarAddCoins.js, scripts/loadSaveGame.js
This PR contains the first half of autosaving (Saving customer board and game board automatically). The second PR being part 2 will implement saving points once the points PR has been commited. 
[Video of what it does now](https://drive.google.com/file/d/1wFd3cCGhS0o5p0AaGxhAfOtWAkUfYjut/view?usp=sharing)
(Goal here was to stop auto populating coins when a returning player joins because new populated coins would count as apart of new save and I don't like clutter. Just say no to clutter! ;P)
=> Fixes duplication bug + Part 1 of autosaving

index.html, scripts/custCoinCheck.js, scripts/moveCoin.js, scripts/scoreSystem.js
Added score systemSystem.js along with calls to the functions in custCoinCheck.js and moveCoin.js to update the score area.
=> [finishes: #185035236] 

index.html, scripts/loadSaveGame.js, scripts/moveCoin.js, scripts/popUpEvents.js
Current bug (hard to explain): Saves points locally. Refresh and points still there. Value in scoreArea = savedpoints value but at same time scoreArea = 0. How and where this is coming from, not really sure.
Note: Something I still have yet to solve is where scoreArea was definded because it looks like it was used somehow but I don't see anywhere it's defined as document.getelementbyid(scoreArea);
=> [finishes: #185084021] Bug: ask ErrorDeleted

scripts/coinJarAddCoins.js, scripts/coinPile.js, scripts/coinProperties.js, scripts/custCoinCheck.js, scripts/customer.js, scripts/loadSaveGame.js, scripts/moveCoin.js, scripts/scoreSystem.js
The coin jar now spawns more coins, at random.
Per spawned coin:
75% 1-2 pennies
15% 3-4 pennies
8% 1 nickel
2% 1-2 dimes
=> [finishes #185141029] Coin Jar spawns more

index.html, scripts/loadSaveGame.js, scripts/shopControl.js, styles/site.css
Features Added:
- No more locks, with titles: Buy Me, Equip Me, Equipped
- All types are saved within autosave/autoload
- Cannot equip more than one item of the same type
https://github.com/harmonymaves/CAPSTONE_coinMerge/assets/123593329/6b34e024-aa1b-4ca5-86f2-b0aeaf7358fb
=> [finishes: #185115181] Let's page load -> Loads new stuff

index.html, styles/site.css
=> updated text and fixed some overflow
